### ISSUE TITLE
Why so little?

### ISSUE THREAD

**Issue by maddox** [ruckage/nes-mini-theme-launch-images-for-retropie#1]
These are really great! But, why are they so tiny? Why aren't they 1920x1080?

Am I missing something? Thanks so much for the great themes!

**Comment by ruckage** [comment]
They're pixel art style so if I scaled them up to 1920x1080 you wouldn't gain any detail, they'd just be a larger file size.  Retropie scales these up to full screen so they don't need to be bigger.

**Comment by maddox** [comment]
Hmm, I just assumed if they were full screen launch images, they’d be native res. I get that they’re pixel art, but I expect them to just be blurry when scaled up. 

I’ll check them out, thanks!

**Comment by ruckage** [comment]
They won't be blurry, I would have pre-scaled them if that was the case.  Retropie doesn't apply any filtering when scaling launch images so they remain crisp. If you check the art in my nes/snes themes you'll see that's also very low resolution.

**Comment by maddox** [comment]
Ok awesome.
